name: 'AzureBicepDeploy'
 
on:
  workflow_dispatch:

  push:
    branches:
    - workflow-new

  pull_request:
    branches:
    - main
    paths:
    - 'bicep/**'
 
jobs:
  validate_bicep:
    name: "Validate Bicep files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./bicep
