name: 'AzureBicepDeploy'
 
on:
  workflow_dispatch:

  push:
    branches:
    - workflow-new

  pull_request:
    branches:
    - main
    paths:
    - 'bicep/'
 
jobs:
  validate_bicep:
    name: "Validate Bicep files"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./bicep

  build-and-deploy:
      runs-on: ubuntu-latest
      needs: validate_bicep

      steps:

        # Checkout code
      - name: Checkout the code
        uses: actions/checkout@main

      - name: Install yq to parse yaml file
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.5.0/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
    
      - name: Parse config.yaml as output to GitHub Actions matrix
        run: |
          echo "config=$(yq e ./bicep/config.yml -j -I=0)" >> $GITHUB_ENV  
  
      - name: Write deployment information to log
        run: |
          echo "Deploying to ${{ fromJson(env.config).AZURE_LOCATION }} with name prefix ${{ fromJson(env.config).RESOURCE_NAME_PREFIX }} and environment tag ${{ fromJson(env.config).ENVIRONMENT_TAG }}"
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Preflight Validation
        working-directory: ./bicep
        run: |
            az deployment sub validate \
              --location ${{ fromJson(env.config).AZURE_LOCATION }} \
              --parameters workloadName=${{ fromJson(env.config).RESOURCE_NAME_PREFIX }} environment=${{ fromJson(env.config).ENVIRONMENT_TAG }} \
              --template-file main.bicep
 
        # Deploy Bicep file, need to point parameters to the main.parameters.json location
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ fromJson(env.config).AZURE_LOCATION }}
          template: ./bicep/main.bicep
          parameters: > 
            workloadName=${{ fromJson(env.config).RESOURCE_NAME_PREFIX }} environment=${{ fromJson(env.config).ENVIRONMENT_TAG }} 
  Generate-ARM:
    name: "Generate ARM Template"
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Exporting ARM template from the bicep file
      - name: Export ARM template
        working-directory: ./bicep
        run : |
          pwd
          az bicep build --file main.bicep --outfile ./azure-resource-manager/integration-arm.json
          ls -al
      # Uploading exported ARM template to GitHub's artifact 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: integration-arm
          path: /arm/integration-arm.json
          retention-days: 2

      # Committing and pushing exported ARM template to the same repo.
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: APIM-Action
          author_email: arekbar@microsoft.com
          message: 'ARM template updated'
          cwd: '/azure-resource-manager/'
          branch_mode: create
          branch: 'arm-${{github.run_number}}'
          add: 'integration-arm.json'